// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ablymessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBStruct;
GPB_ENUM_FWD_DECLARE(CodecDataType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AblymessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AblymessageRoot : GPBRootObject
@end

#pragma mark - AblyMessage

typedef GPB_ENUM(AblyMessage_FieldNumber) {
  AblyMessage_FieldNumber_RegistrationHandle = 1,
  AblyMessage_FieldNumber_MessageType = 2,
  AblyMessage_FieldNumber_Message = 3,
};

@interface AblyMessage : GPBMessage

@property(nonatomic, readwrite) int64_t registrationHandle;

@property(nonatomic, readwrite) enum CodecDataType messageType;

@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

/**
 * Fetches the raw value of a @c AblyMessage's @c messageType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AblyMessage_MessageType_RawValue(AblyMessage *message);
/**
 * Sets the raw value of an @c AblyMessage's @c messageType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAblyMessage_MessageType_RawValue(AblyMessage *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
