// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBTimestamp;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TokenRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TokenRoot : GPBRootObject
@end

#pragma mark - TokenDetails

typedef GPB_ENUM(TokenDetails_FieldNumber) {
  TokenDetails_FieldNumber_Token = 1,
  TokenDetails_FieldNumber_Expires = 2,
  TokenDetails_FieldNumber_Issued = 3,
  TokenDetails_FieldNumber_Capability = 4,
  TokenDetails_FieldNumber_ClientId = 5,
};

@interface TokenDetails : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite) uint32_t expires;

@property(nonatomic, readwrite) uint32_t issued;

@property(nonatomic, readwrite, copy, null_resettable) NSString *capability;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@end

#pragma mark - TokenParams

typedef GPB_ENUM(TokenParams_FieldNumber) {
  TokenParams_FieldNumber_Capability = 1,
  TokenParams_FieldNumber_ClientId = 2,
  TokenParams_FieldNumber_Nonce = 3,
  TokenParams_FieldNumber_Timestamp = 4,
  TokenParams_FieldNumber_Ttl = 5,
};

@interface TokenParams : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *capability;

@property(nonatomic, readwrite, copy, null_resettable) NSString *clientId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nonce;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *timestamp;
/** Test to see if @c timestamp has been set. */
@property(nonatomic, readwrite) BOOL hasTimestamp;

@property(nonatomic, readwrite) uint32_t ttl;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
