import 'src/ably_implementation.dart';

abstract class Ably {
  factory Ably() => AblyImplementation();

  Future<String> get platformVersion;
  Future<String> get version;
  Future<Realtime> createRealtime(final ClientOptions options);
}

/// Interface implemented by event listeners, returned by event emitters.
abstract class EventListener<E> {
  /// Register for all events (no parameter), or a specific event.
  Stream<E> on([E event]);

  /// Register for a single occurrence of any event (no parameter), or a specific event.
  Future<E> once([E event]);

  /// Remove registrations for this listener, irrespective of type.
  Future<void> off();
}

/// Interface implemented by Ably classes that can emit events, offering the capability
/// to create listeners for those events.
abstract class EventEmitter<E> {
  /// Remove all listener registrations, irrespective of type.
  Future<void> off();

  /// Create a listener, with which registrations may be made.
  Future<EventListener<E>> createListener();
}

enum ConnectionEvent {
	initialized,
	connecting,
	connected,
	disconnected,
	suspended,
	closing,
	closed,
	failed,
	update,
}

abstract class Connection implements EventEmitter<ConnectionEvent> {
}

abstract class Channels {
}

abstract class Realtime {

  Realtime(this.connection, this.channels);

  final Connection connection;
  final Channels channels;

  Future<void> connect();
  void close();
}

/// Java: io.ably.lib.rest.Auth.TokenDetails
class AuthTokenDetails {
  String token;
  int expires;
  int issued;
  String capability;
  String clientId;
}

/// Java: io.ably.lib.rest.Auth.TokenParams
class AuthTokenParams {
  int ttl;
  String capability;
  String clientId;
  int timestamp;
}

/// Function-type alias implemented by a function that provides either tokens,
/// or signed token requests, in response to a request with given token params.
/// 
/// Java: io.ably.lib.rest.Auth.TokenCallback.getTokenRequest(TokenParams)
typedef dynamic AuthCallback(AuthTokenParams params);

/// Java: io.ably.lib.rest.Auth.AuthOptions
class AuthOptions {
  AuthCallback authCallback;
  String authUrl;
  String authMethod;
  String key;
  AuthTokenDetails tokenDetails;
  Map<String, String> authHeaders;
  Map<String, String> authParams;
  bool queryTime;
  bool useAuthToken;
}

/// Java: io.ably.lib.http.HttpAuth.Type
enum HttpAuthType {
  BASIC,
  DIGEST,
  X_ABLY_TOKEN,
}

/// Java: io.ably.lib.types.ProxyOptions
class ProxyOptions {
  String host;
  int port;
  String username;
  String password;
  List<String> nonProxyHosts;
  HttpAuthType prefAuthType;
}

/// Java: io.ably.lib.transport.Defaults
abstract class TransportDefaults {
  static const int HTTP_ASYNC_THREADPOOL_SIZE = 64;
}

/// An exception generated by the client library SDK called by this plugin.
class LibraryException implements Exception {
}

typedef LogHandler(int severity, String tag, String message, LibraryException exception);

/// Java: io.ably.lib.rest.Auth.TokenParams
class ClientOptions extends AuthOptions {
  String clientId;
  int logLevel;
  LogHandler logHandler;
  bool tls;
  String restHost;
  String realtimeHost;
  int port;
  int tlsPort;
  bool autoConnect;
  bool useBinaryProtocol;
  bool queueMessages;
  bool echoMessages;
  String recover;
  ProxyOptions proxy;
  String environment;
  bool idempotentRestPublishing;
  int httpOpenTimeout;
  int httpRequestTimeout;
  int httpMaxRetryCount;
  int realtimeRequestTimeout;
  List<String> fallbackHosts;
  bool fallbackHostsUseDefault;
  int fallbackRetryTimeout;
  AuthTokenParams defaultTokenParams;
  int channelRetryTimeout;
  Map<String, String> transportParams;
  int asyncHttpThreadpoolSize;
  bool pushFullWait;
}
