import 'package:ably_flutter/ably_flutter.dart';
import 'package:meta/meta.dart';

/// BEGIN LEGACY DOCSTRING
/// Current state of the device in respect of it being a target for
/// push notifications.
///
/// https://docs.ably.com/client-lib-development-guide/features/#RSH8
/// END LEGACY DOCSTRING

/// BEGIN EDITED CANONICAL DOCSTRING
/// Contains the device identity token and secret of a device. `LocalDevice`
/// extends [DeviceDetails].
/// END EDITED CANONICAL DOCSTRING
@immutable
class LocalDevice extends DeviceDetails {
  /// BEGIN LEGACY DOCSTRING
  /// Device token. Generated locally, if not available.
  /// END LEGACY DOCSTRING

  /// BEGIN EDITED CANONICAL DOCSTRING
  /// A unique device secret generated by the Ably SDK.
  /// END EDITED CANONICAL DOCSTRING
  final String? deviceSecret;

  /// BEGIN LEGACY DOCSTRING
  /// A token generated by Ably to authenticate the device.
  ///
  /// Previously called `deviceToken`, but this was ambiguous because it
  /// overlaps with APNs device token. Now both terms exist in implementations
  /// Use `X-Ably-DeviceToken` when authenticating with Ably.
  /// END LEGACY DOCSTRING

  /// BEGIN EDITED CANONICAL DOCSTRING
  /// A unique device identity token used to communicate with APNS or FCM.
  /// END EDITED CANONICAL DOCSTRING
  final String? deviceIdentityToken;

  /// BEGIN LEGACY DOCSTRING
  /// Initializes an instance without any defaults
  /// END LEGACY DOCSTRING
  LocalDevice({
    required DeviceDetails deviceDetails,
    this.deviceIdentityToken,
    this.deviceSecret,
  }) : super(
          clientId: deviceDetails.clientId,
          formFactor: deviceDetails.formFactor,
          id: deviceDetails.id,
          metadata: deviceDetails.metadata,
          platform: deviceDetails.platform,
          push: deviceDetails.push,
        );
}
