import 'package:ably_flutter/ably_flutter.dart';
import 'package:meta/meta.dart';

/// BEGIN EDITED CANONICAL DOCSTRING
/// Contains the device identity token and secret of a device. `LocalDevice`
/// extends [DeviceDetails].
/// END EDITED CANONICAL DOCSTRING
@immutable
class LocalDevice extends DeviceDetails {
  /// BEGIN EDITED CANONICAL DOCSTRING
  /// A unique device secret generated by the Ably SDK.
  /// END EDITED CANONICAL DOCSTRING
  final String? deviceSecret;

  /// BEGIN EDITED CANONICAL DOCSTRING
  /// A unique device identity token used to communicate with APNS or FCM.
  /// END EDITED CANONICAL DOCSTRING
  final String? deviceIdentityToken;

  /// BEGIN LEGACY DOCSTRING
  /// @nodoc
  /// Initializes an instance without any defaults
  /// END LEGACY DOCSTRING
  LocalDevice({
    required DeviceDetails deviceDetails,
    this.deviceIdentityToken,
    this.deviceSecret,
  }) : super(
          clientId: deviceDetails.clientId,
          formFactor: deviceDetails.formFactor,
          id: deviceDetails.id,
          metadata: deviceDetails.metadata,
          platform: deviceDetails.platform,
          push: deviceDetails.push,
        );
}
