#!/bin/sh

set -e
set -o pipefail

MY_PATH=$(pwd)

echo "Checking formatting of Dart, Swift and Java files, without modifying them."
echo "❓ To format files, run '. format-files.sh'\n" # Objective-C files are not checked.

# Redirect output to stderr.
exec 1>&2

# Pre-requisites
# 1. You should have Flutter installed (e.g. in `/opt/flutter`) and on your PATH. This provides the Dart formatting tool, `flutter format`.
if ! [ -x "$(command -v flutter)" ]; then
  echo "🚨 FAILURE: Missing dependency, you must install Flutter, download it from https://docs.flutter.dev/get-started/install/macos" >&2
  exit 1
fi

# 2. Download the release from https://github.com/google/google-java-format/releases, and update your environment variable. This provides the Java formatting tool.
if [ "$GOOGLE_JAVA_FORMAT_PATH" = "" ]; then
  echo "🚨 FAILURE: You must download https://github.com/google/google-java-format/releases and set GOOGLE_JAVA_FORMAT_PATH to the jar you downloaded.";
  exit 1;
fi

# 3. Install using brew by running `brew install swiftformat`. This provides the Swift formatting tool.
if ! [ -x "$(command -v swiftformat)" ]; then
  echo "🚨 FAILURE: Missing dependency, you must install swiftformat, e.g. run 'brew install swiftformat'" >&2
  exit 1
fi

echo "❓ Dart file formatting being checked..."
/opt/flutter/bin/flutter format --set-exit-if-changed $MY_PATH
echo "✅ Dart file formatting checked. \n"

echo "❓ Java file formatting being checked..."
JAVA_FILES=$(find $MY_PATH -name "*java" -type f -exec ls {} \;)
echo $JAVA_FILES | xargs java \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  -jar $GOOGLE_JAVA_FORMAT_PATH --set-exit-if-changed --dry-run
echo "✅ Java file formatting checked. \n"

echo "❓ Swift file formatting being checked..."
swiftformat --lint --swiftversion 5.5 $MY_PATH
echo "✅ Swift file formatting checked. \n"