on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version: '3.24'
          cache: true

      - name: Use Intro Blurb As Homepage
        run: |
          mv README.md README.md.bak
          mv API_REF_INTRO_BLURB.md README.md

      - name: Build Documentation
        run: |
          dart doc
          ls -al doc/api

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.ABLY_AWS_ACCOUNT_ID_SDK }}:role/ably-sdk-builds-ably-flutter
          role-session-name: "${{ github.run_id }}-${{ github.run_number }}"

      - name: Upload Documentation
        uses: ably/sdk-upload-action@8c6179796fc7ee8fc9bb28d5223ffef005b985cc # v1.3.0
        with:
          sourcePath: doc/api
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: dartdoc

      - name: Restore Readme
        run: |
          mv README.md API_REF_INTRO_BLURB.md
          mv README.md.bak README.md
