on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version: '3.29'
          cache: true

      # test_integration package depends on ably_flutter, so before we run integration
      # tests it's best to perform dependency update in both packages, to make sure that
      # integration tests are run with exactly the same dependencies as specified in
      # current version of ably_flutter package
      - name: Update dependencies
        run: |
          flutter pub get
          cd test_integration && flutter pub get

      - name: Build iOS app (no simulator needed yet)
        working-directory: test_integration
        run: flutter build ios --simulator

      - name: Pick simulator
        run: |
          DEVICE=$(xcrun simctl list devices available | \
            grep -E "iPhone" | head -n 1)
          echo $DEVICE
          UDID=$(echo $DEVICE | sed -E 's/.*\(([A-F0-9-]+)\).*/\1/')
          echo "SIMULATOR_ID=$UDID" >> $GITHUB_ENV

      - name: Boot simulator
        timeout-minutes: 5
        run: |
          xcrun simctl boot "$SIMULATOR_ID" || true
          xcrun simctl bootstatus "$SIMULATOR_ID" -b

      - name: Run integration tests (no rebuild)
        timeout-minutes: 25
        working-directory: test_integration
        run: |
          flutter drive --no-pub --no-build \
            --use-application-binary=build/ios/iphonesimulator/Runner.app \
            -d $SIMULATOR_ID

  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [24, 29]
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          flutter-version: '3.29'
          cache: true

      - name: 'Run Flutter Driver tests'
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@e89f39f1abbbd05b1113a29cf4db69e7540cae5a # v2.37.0
        with:
          api-level: ${{ matrix.api-level }}
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            flutter pub get
            cd test_integration && flutter build apk && flutter drive
