on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ios:
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24"
          cache: true

      - name: "Build example app for iOS"
        run: |
          flutter pub get
          cd example && flutter build ios --no-codesign

  android:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24"
          cache: true

      - name: "Build example app for Android"
        run: |
          flutter pub get
          cd example && flutter build apk
