name: Release

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Verify plugin format
        run: flutter format --set-exit-if-changed .

      - name: Run pub publish dry-run
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        run: echo "${{ secrets.PUB_DEV_PUBLISH_TOKEN }}" | flutter pub publish --force --access-token